In [28]:
import numpy as np
#1.將下列清單(list1)，轉成維度為(5X6)的array，順序按列填充。(hint:order="F")
array1 = np.array(range(30))
# print(array1)
print("\nReshape array1 to 5*6")
arr1 = array1.reshape(5, 6)
print(arr1)
print()
#2.呈上題的array，找出被6除餘1的數的索引
index = np.array(np.where(arr1%6 == 1))
# print(index)
print("\nArg of number in array1 which mod 6 equals to 1 :") 
arr = np.array(index.flat)
for n in range(int(index.size/2)):
    m = int(n + index.size/2) 
    st = str(arr[n]) + " " + str(arr[m])
    print(st)
    
    






Reshape array1 to 5*6
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


Arg of number in array1 which mod 6 equals to 1 :
0 1
1 1
2 1
3 1
4 1
